set nu
set laststatus=2
source /Users/freitasr/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim/plugin/powerline.vim
set mouse=a
set nocompatible
set backspace=2
syntax on
set softtabstop=2
set expandtab
set wildmenu
