set nu
set laststatus=2
source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim
set mouse=a
set nocompatible
set backspace=2
syntax on
set softtabstop=2
set expandtab
set wildmenu
