#!/usr/bin/env ruby

class RailsCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def projects
    `ls ~/dev/rails`.split
  end
end

puts RailsCompletion.new(ENV["COMP_LINE"]).matches
exit 0
